import { createClient } from '@supabase/supabase-js';

// This file is automatically generated. Do not edit it directly.
const SUPABASE_URL = "https://vilknsbrvakthefsgfwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpbGtuc2JydmFrdGhlZnNnZndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4ODk1MTUsImV4cCI6MjA4NzQ2NTUxNX0.kCmNQ43Vcl0Im0yL8mawB5HqhTO63bKfT-RaaivWjvA";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);